spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      auto-commit: false
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog.xml